/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mothershipattendance;

import java.awt.Component;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *  A Confirmation Message JFrame Form That is Used to
 *  Let the User Know When A Student's Information Has
 *  Been Found and asks them to Confirm Whether or not
 *  they wish to add the student to the currently chosen
 *  class. There are Two Separate Sets of Type Integers
 *  That this Class Can be Called With. Their
 *  Details are Displayed Below:
 * 
 *  Table Type Selection Value:   0     This Window is Being Called from
 *                                      the Students In Class JTable Menu
 *                                      located Within the Manage Student
 *                                      Access Panel of the Management Tab.
 * 
 *  Table Type Selection Value:   1     This Window is Being Called from
 *                                      the All Students JTable Menu
 *                                      located Within the Manage Student
 *                                      Access Panel of the Management Tab.
 * 
 *  Add By Type Value:   0              This Window is Being Called from
 *                                      the Students In Class JTable Menu
 *                                      and the User is trying to Add the
 *                                      Student to the Class By Entering
 *                                      their Username.
 * 
 *  Add By Type Value:   1              This Window is Being Called from
 *                                      the Students In Class JTable Menu
 *                                      and the User is trying to Add the
 *                                      Student to the Class By Entering
 *                                      their Student Identification Number.
 * 
 *  @author     Tyler Fontana
 *  @date       October 16 2020
 *  @version    1.0.3
 * 
 */
public class AddStudentConfirmationMessage extends javax.swing.JFrame {

    /**
     *  Create the New JFrame Form Along with
     *  Setting the Type of the Current Calling
     *  Table Menu.
     * 
     *  @param value    The Type of Table Calling
     *                  Menu, this value is used to
     *                  determine which synchronized
     *                  methods should be called.
     */
    public AddStudentConfirmationMessage(int tableView, int value) {
        // The Table View Type Which is Calling
        // the JFrame Confirmation Message Form
        tableTypeSelection = tableView;
        // Set Table Menu Type
        addByType = value;
        // Set JFrame Form Details.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmation Screen");
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(450, 294));
        setName("WarningFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("The Password Entered Is Incorrect.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        getContentPane().add(jPanel4);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/steelbackground428x202.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        // The Calling Form is the Students In Class
        // Table Segment.
        if (tableTypeSelection == 0) {
            // If We Are Adding A Student
            // By Thier Username
            if (addByType == 0) {
                // If Cancel Option Has Been Clicked, Change Message Response Tracker
                // Value to 3 Which Symbolizes that the User Has chosen to Cancel the
                // Add Student Operation in the Students In Class Table Section.
                if (messageResponseTracker.getAddStudentResponseStudentsInClassAddByUsernameSegmentValue() == 0) {
                    // Show that the user has chosen to cancel the operation
                    // so that the currently running ManageStudents TaskHandler
                    // Thread knows how to respond.
                    messageResponseTracker.setAddStudentResponseStudentsInClassAddByUsernameSegmentValue(3);
                }
            }
            // If We Are Adding A Student
            // By Thier Identification Number
            else if (addByType == 1) {
                // If Cancel Option Has Been Clicked, Change Message Response Tracker
                // Value to 3 Which Symbolizes that the User Has chosen to Cancel the
                // Add Student Operation in the All Students Table Section.
                if (messageResponseTracker.getAddStudentResponseStudentsInClassAddByStudentIDSegmentValue() == 0) {
                    // Show that the user has chosen to cancel the operation
                    // so that the currently running ManageStudents TaskHandler
                    // Thread knows how to respond.
                    messageResponseTracker.setAddStudentResponseStudentsInClassAddByStudentIDSegmentValue(3);
                }
            }
        }
        // The Calling Form is the All Students
        // Table Segment.
        else if (tableTypeSelection == 1) {
            
            // If Cancel Option Has Been Clicked, Change Message Response Tracker
            // Value to 3 Which Symbolizes that the User Has chosen to Cancel the
            // Add Student Operation in the All Students Table Section.
            if (messageResponseTracker.getAddStudentResponseAllStudentsSegmentValue() == 0) {
                // Show that the user has chosen to cancel the operation
                // so that the currently running ManageStudents TaskHandler
                // Thread knows how to respond.
                messageResponseTracker.setAddStudentResponseAllStudentsSegmentValue(3);
            }
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Retrieve A Reference to the Current Instance
        // of the MainScreen Class.
        main = classInstanceTracker.getMainScreenInstance();

        // Bring Popup Window Form to the 
        // Front of the Application.
        super.toFront();
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    /**
     *  Method that is invoked should a user Click
     *  the YES Button Within the Add Student Confirmation
     *  Message JFrame Window.
     * 
     *  @param evt          The User's Clicking of the Action
     *                      (YES) Button.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Yes Clicked");
        // The Calling Form is the Students In Class
        // Table Segment.
        if (tableTypeSelection == 0) {
            // If We Are Adding A Student
            // By Thier Username
            if (addByType == 0) {
                // Yes Clicked
                messageResponseTracker.setAddStudentResponseStudentsInClassAddByUsernameSegmentValue(1);
            }
            // If We Are Adding A Student
            // By Thier Identififcation Number
            else if (addByType == 1) {
                // Yes Clicked
                messageResponseTracker.setAddStudentResponseStudentsInClassAddByStudentIDSegmentValue(1);
            }
        }
        // The Calling Form is the All Students
        // Table Segment.
        else if (tableTypeSelection == 1) {
            // Yes Clicked
            messageResponseTracker.setAddStudentResponseAllStudentsSegmentValue(1);
        }
        
        // Close JFrame Form And
        // Activate Window Closed
        // Method.
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *  Method that is invoked should a user Click
     *  the NO Button Within the Add Student Confirmation
     *  Message JFrame Window.
     * 
     *  @param evt          The User's Clicking of the Action
     *                      (NO) Button.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // The Calling Form is the Students In Class
        // Table Segment.
        if (tableTypeSelection == 0) {
            // If We Are Adding A Student
            // By Thier Username
            if (addByType == 0) {
                // No Clicked
                messageResponseTracker.setAddStudentResponseStudentsInClassAddByUsernameSegmentValue(2);
            }
            // If We Are Adding A Student
            // By Thier Identififcation Number
            else if (addByType == 1) {
                // No Clicked
                messageResponseTracker.setAddStudentResponseStudentsInClassAddByStudentIDSegmentValue(2);
            }
        }
        // The Calling Form is the All Students
        // Table Segment.
        else if (tableTypeSelection == 1) {
            // No Clicked
            messageResponseTracker.setAddStudentResponseAllStudentsSegmentValue(2);
        }
        
        // Close JFrame Form And
        // Activate Window Closed
        // Method.
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentConfirmationMessage(-1, -1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    public Point newLocation;
    public int tableTypeSelection;
    public int addByType;
    
    public MainScreen main;
    public MessageResponseTracker messageResponseTracker = new MessageResponseTracker();
    public DatabaseManagerMySQL manager = new DatabaseManagerMySQL();
    public ClassInstanceInformationTracker classInstanceTracker = new ClassInstanceInformationTracker();
}
