/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mothershipattendance;


import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author tylerfontana
 */
public class ChatPanelRenderer extends javax.swing.JPanel implements ListCellRenderer<ChatPanel> {

    /**
     * Creates new form ChatPanelGUI
     */
    public ChatPanelRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel37 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ServerInformationTracker serverTracker = new ServerInformationTracker();
        
        jTextArea1.setOpaque(false);
        jTextArea1.setBorder(null);

        if (serverTracker.getChatTextAreaSize() == 1) {
            
            System.out.println("We Are Getting Here in the ChatRenderer Class 1");
            
            jPanel37.setBackground(new java.awt.Color(255, 255, 255));
            jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel37.setMaximumSize(new java.awt.Dimension(750, 350));
            jPanel37.setMinimumSize(new java.awt.Dimension(750, 350));
            jPanel37.setSize(new java.awt.Dimension(750, 350));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/ProfilePictures/XSChatIcons/serverIcon48x48.png"))); // NOI18N

            jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
            jLabel2.setText("Tyler Fontana");

            jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
            jLabel3.setText("14:02:03");

            jScrollPane2.setBorder(null);
            jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

            jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
            jTextArea1.setColumns(20);
            jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(40);
            jTextArea1.setText("Mr oh winding it enjoyed by between. The servants securing material goodness her. Saw principles themselves ten are possession. So endeavor to continue cheerful doubtful we to. Turned advice the set vanity why mutual. Reasonably if conviction on be unsatiable discretion apartments delightful. Are melancholy appearance stimulated occasional entreaties end. Shy ham had esteem happen active county. Winding morning am shyness evident to. Garrets because elderly new manners however one village she.");
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setBorder(null);
            jScrollPane2.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
            jPanel37.setLayout(jPanel37Layout);
            jPanel37Layout.setHorizontalGroup(
                jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane2))
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addGap(22, 22, 22)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(25, 25, 25))
            );
            jPanel37Layout.setVerticalGroup(
                jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
        }
        else {
            
            System.out.println("We Are Getting Here in the ChatRenderer Class 2");
            
            jPanel37.setBackground(new java.awt.Color(255, 255, 255));
            jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel37.setMaximumSize(new java.awt.Dimension(750, 350));
            jPanel37.setMinimumSize(new java.awt.Dimension(750, 350));
            jPanel37.setSize(new java.awt.Dimension(750, 350));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/ProfilePictures/XSChatIcons/serverIcon48x48.png"))); // NOI18N

            jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
            jLabel2.setText("Tyler Fontana");

            jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
            jLabel3.setText("14:02:03");

            jScrollPane2.setBorder(null);
            jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

            jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
            jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
            jTextArea1.setColumns(20);
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(40);
            jTextArea1.setText("");
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setBorder(null);
            jScrollPane2.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
            jPanel37.setLayout(jPanel37Layout);
            jPanel37Layout.setHorizontalGroup(
                jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane2))
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addGap(22, 22, 22)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(25, 25, 25))
            );
            jPanel37Layout.setVerticalGroup(
                jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel37Layout.createSequentialGroup()
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel37Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
        }
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   

    @Override
    public Component getListCellRendererComponent(JList<? extends ChatPanel> list, ChatPanel value, int index, boolean isSelected, boolean cellHasFocus) {
        
        this.jLabel1.setIcon(value.getImageIcon());
        this.jLabel2.setText(value.getUsername());
        this.jLabel3.setText(value.getTimestamp());
        this.jTextArea1.setText(value.getMessage());
        
        /*if (this.jTextArea1.getLineCount() == 1) {
            
            Dimension dimensionTextArea = this.jTextArea1.getSize();
            Dimension dimensionJPanel37 = this.jPanel37.getSize();
            
            dimensionTextArea.setSize(new Dimension((int) dimensionTextArea.getWidth(), 22));
            dimensionJPanel37.setSize(new Dimension((int) dimensionJPanel37.getWidth(), 114));
            
            this.jTextArea1.setPreferredSize(dimensionTextArea);
            this.jTextArea1.setMaximumSize(dimensionTextArea);
            this.jTextArea1.setMaximumSize(dimensionTextArea);
            this.jTextArea1.setSize(dimensionTextArea);
            
            this.jPanel37.setPreferredSize(dimensionJPanel37);
            this.jPanel37.setMaximumSize(dimensionJPanel37);
            this.jPanel37.setMinimumSize(dimensionJPanel37);
            this.jPanel37.setSize(dimensionJPanel37);
            
            this.jTextArea1.revalidate();
            this.jPanel37.revalidate();
            
        }
        else if (this.jTextArea1.getLineCount() == 2) {
            
        }
        else if (this.jTextArea1.getLineCount() == 3) {
            
        }
        else if (this.jTextArea1.getLineCount() == 4) {
            
        }
        else {
            
        }
        
        System.out.println("number of lines" + this.jTextArea1.getLineCount());
        //this.jPanel37.setPreferredSize(preferredSize);*/
        
        return this;
    }
}
