/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mothershipattendance;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingWorker;

/**
 *
 * @author tylerfontana
 */
public class DeleteClassPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewClassJPanel
     */
    public DeleteClassPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(829, 360));
        setMinimumSize(new java.awt.Dimension(829, 360));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(829, 360));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new javax.swing.OverlayLayout(this));

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Select The Class You Wish Delete:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(236, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        add(jPanel1);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(264, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );

        add(jPanel2);

        jPanel3.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Delete Class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(354, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(165, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );

        add(jPanel3);

        jPanel5.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/refreshIcon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(574, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        add(jPanel5);

        jPanel4.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/PanelBackdrop829x360.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main = serverTracker.getMainScreenInstance();
        main.showManagementScreenLoaderImage();
        
        setComponentsEnabled(false);
        
        DeleteClassTaskHandler handler = new DeleteClassTaskHandler();
        handler.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        setComponentsEnabled(false);
        
        ArrayList<Integer> classIDs = manager.getInstructorClassListIDs(tracker.getCurrentInstructorInformation().getInstructorID());
        ArrayList<ClassType> classes = manager.getInstructorClassList(classIDs);

        ClassType noClassesClassType = new ClassType(0, "NULL", 0, " ------- No Associated Classes ------ ", "", "", "", "Lecture", "", 0, 0);
        ClassType defaultClassTypeUpdateClassInformationJPanel = new ClassType(0, "NULL", 0, " ------------------------------------- ", "", "", "", "Lecture", "", 0, 0);

        ArrayList<ClassType> recordsTabBoxListOne = new ArrayList<>();

        for (int i = 0; i < classes.size(); i++) {
            if (i == 0) {
                recordsTabBoxListOne.add(classes.get(i));
            }
            else {
                for (int j = 0; j < recordsTabBoxListOne.size(); j++) {
                    if (recordsTabBoxListOne.get(j).getClassTitle().equalsIgnoreCase(classes.get(i).getClassTitle())) {
                        
                        classes.get(i).setDuplicateStatus(true);
                        recordsTabBoxListOne.get(j).setDuplicateStatus(true);
                        
                    }
                }
                
                recordsTabBoxListOne.add(classes.get(i));
            }
        }

        if (recordsTabBoxListOne.isEmpty()) {
            recordsTabBoxListOne.add(0, noClassesClassType);
        }
        else {
            recordsTabBoxListOne.add(0, defaultClassTypeUpdateClassInformationJPanel);
        }

        DefaultComboBoxModel modelBoxOne = new DefaultComboBoxModel(recordsTabBoxListOne.toArray());
        jComboBox1.setModel(modelBoxOne);
        jComboBox1.setSelectedIndex(0);
        
        setComponentsEnabled(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void setComponentsEnabled(boolean value) {
        jComboBox1.setEnabled(value);
        jButton1.setEnabled(value);
        jLabel1.setEnabled(value);
    }
    
    public void updateClassSelectionBox() {
        setComponentsEnabled(false);
        
        ArrayList<Integer> classIDs = manager.getInstructorClassListIDs(tracker.getCurrentInstructorInformation().getInstructorID());
        ArrayList<ClassType> classes = manager.getInstructorClassList(classIDs);

        ClassType noClassesClassType = new ClassType(0, "NULL", 0, " ------- No Associated Classes ------ ", "", "", "", "Lecture", "", 0, 0);
        ClassType defaultClassTypeUpdateClassInformationJPanel = new ClassType(0, "NULL", 0, " ------------------------------------- ", "", "", "", "Lecture", "", 0, 0);

        ArrayList<ClassType> recordsTabBoxListOne = new ArrayList<>();

        for (int i = 0; i < classes.size(); i++) {
            if (i == 0) {
                recordsTabBoxListOne.add(classes.get(i));
            }
            else {
                for (int j = 0; j < recordsTabBoxListOne.size(); j++) {
                    if (recordsTabBoxListOne.get(j).getClassTitle().equalsIgnoreCase(classes.get(i).getClassTitle())) {
                        
                        classes.get(i).setDuplicateStatus(true);
                        recordsTabBoxListOne.get(j).setDuplicateStatus(true);
                        
                    }
                }
                
                recordsTabBoxListOne.add(classes.get(i));
            }
        }

        if (recordsTabBoxListOne.isEmpty()) {
            recordsTabBoxListOne.add(0, noClassesClassType);
        }
        else {
            recordsTabBoxListOne.add(0, defaultClassTypeUpdateClassInformationJPanel);
        }

        DefaultComboBoxModel modelBoxOne = new DefaultComboBoxModel(recordsTabBoxListOne.toArray());
        jComboBox1.setModel(modelBoxOne);
        jComboBox1.setSelectedIndex(0);
        
        setComponentsEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<ClassType> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    public DatabaseManagerMySQL manager = new DatabaseManagerMySQL();
    public ServerInformationTracker serverTracker = new ServerInformationTracker();
    public TrackerObject tracker = new TrackerObject();
    public MainScreen main;
    
    /*
     *  LoadingScreenController is a SwingWorker Class whose
     *  doInBackground() Method is invoked upon calling the execute()
     *  method in the main class. A SwingWorker Class is the only
     *  way to safely create a seperate thread that interacts with
     *  the main EventQueue class. Should you try to invoke change to the GUI
     *  object from a non EventQueue related class, it can cause
     *  unforseen nonrepeatable errors in the programs execution.
     *
     */
    private class DeleteClassTaskHandler extends SwingWorker<Void,Void> {
        
        // Method for Seperate EventQueue Thread
        // to Execute.
        @Override
        protected Void doInBackground() throws Exception {
            
            int selectedIndex = jComboBox1.getSelectedIndex();
        
            if (selectedIndex == 0) {
                WarningMessageManagementCreateNewClass wmmcnc = new WarningMessageManagementCreateNewClass("DeleteClassPanel");
                String htmlConvertedText = "";

                htmlConvertedText = "<html><center>Please Select A Valid Option Before Attempting to Continue.</center></html>";
                wmmcnc.jLabel6.setText(htmlConvertedText);

                wmmcnc.setVisible(true);
            }
            else {

                ClassType classType = jComboBox1.getItemAt(selectedIndex);

                ManagementTabQuestionWindowDeleteClassPanel mtqwdcp = new ManagementTabQuestionWindowDeleteClassPanel(classType.getClassID(), tracker.getCurrentInstructorInformation().getInstructorID());
                String htmlConvertedText = "<html><center>Are You Sure You Want to Delete This Class? (<font color=#00bee5>Note</font>: <font color=#00e50e>This Action Will Delete All Attendance Records Associated With the Class As Well.</font>)</center></html>";
                mtqwdcp.jLabel6.setText(htmlConvertedText);

                main.hideManagementScreenLoaderImage();
                setComponentsEnabled(false);
                
                mtqwdcp.setVisible(true);
            }
            
            return null;
        }
        
        // This method is automatically invoked after the
        // doInBackground() method has finished
        // executing.
        @Override
        protected void done() {
            // Make the GuiFour Frame
            // invisible.
            //setVisible(false);
            //dispose();
        }
    }
}
