/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mothershipattendance;

import javax.swing.SwingWorker;

/**
 *  This Class is Responsible for Creating a Pop-Up GUI
 *  Status Message which Alerts the User of What Type of
 *  Error Has Occurred During either the Instructor or 
 *  Student Account Creation Process. This Warning / 
 *  Status Message GUI Class is Instantiated With an
 *  Error Type Integer Value Which Allows it to Know 
 *  Which Process to Execute Upon Disposal, in Addition
 *  to a Form Type Integer Value Which Tells the GUI
 *  Window Which Account Creation Form Has Invoked it.
 * 
 *  @date           November 10, 2020
 *  @author         Tyler Fontana
 *  @version        1.0.2
 */
public class StatusMessageAccountCreation extends javax.swing.JFrame {

    /**
     *  This Basic Constructor Creates a new Instance of
     *  the Status Message Account Creation GUI Class. The First
     *  Parameter Integer Value Passed in Acts as the Status
     *  Message Number Type which Tells the Class What Task to
     *  Accomplish on Window Disposal. The Second Parameter Value
     *  Lets the GUI Window Know Which Account Creation Window
     *  Form Has Created the Window.
     * 
     *  @param v1               The Error / Status Message
     *                          Number Which Lets the Pop-Up
     *                          Window Know Which Task to
     *                          Accomplish on Window Disposal.
     * 
     *  @param v2               The Form Type Integer Value
     *                          Which Lets the Status Message
     *                          Window Know Which Account Creation
     *                          GUI Window Form has Created it.
     *
     *  @param v3               The Boolean Array Containing the
     *                          Validity Check Result Values. This
     *                          May Be Used if Multiple Fields 
     *                          Contain Invalid Characters.
     */
    public StatusMessageAccountCreation(int v1, int v2, boolean[] v3) {
        // Set the Error / Status Message Type.
        messageType = v1;
        // Set the Account Creation Form Type.
        formType = v2;
        // Save Validity Results Array.
        results = v3;
        /**
         * Invoke the Method Used to Create and
         * Display the GUI Window Form.
         **/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Warning Screen");
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(450, 294));
        setName("WarningFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><center>Multiple Fields Contain Missing or Incorrect Information. Please Ensure that you have Entered a Response in Every Required Information Field.</center></html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/warningemblemscaled.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/steelbackground356x112.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *  This Method is Automatically Invoked Whenever the User
     *  Closes the current Status Message GUI Window Instance, or
     *  the dispose() method is invoked somewhere within the Class.
     *  This Method is Responsible for Creating and Executing a
     *  Background Event Queue Thread Which is Responsible for
     *  Manipulating the Specified Account Creation GUI Window 
     *  Form's Aesthetics.
     * 
     *  @param evt              The Action of the Current Window Instance
     *                          Closing either Programmatically or through
     *                          User intervention / Response.
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        /**
         *  Execute a new Background Event Queue Thread
         *  which will Accomplish the Heavy Window Form 
         *  Manipulation Tasks Upon Window Disposal.
         */
        new TaskHandler(messageType).execute();        
    }//GEN-LAST:event_formWindowClosed

    /**
     *  This Method is Used to Request that the Focus
     *  of the Credentials Screen GUI Form is Moved to
     *  the "Login" JButton Upon the Disposal of the
     *  Status Message GUI Screen. This is done so that
     *  the Highlighted Error Fields aren't Automatically
     *  Removed by the Form Placing the Overall Event
     *  Queue Thread's Focus on the "Username" Field.
     */
    public void requestFocusOnAccountCreationButtonComponent() {
        /**
         *  If the "Instructor" Version of the
         *  Account Creation Window is the GUI
         *  Class Which Spawned the Status Message
         *  GUI Window.
         */
        if (formType == 0) {
            // Request Focus to be Placed on "Create Account" Button.
            AccountCreationInstructor.jButton1.requestFocusInWindow();
        }
        /**
         *  If the "Student" Version of the
         *  Account Creation Window is the GUI
         *  Class Which Spawned the Status Message
         *  GUI Window.
         */
        else if (formType == 1) {
            // Request Focus to be Placed on "Create Account" Button.
            AccountCreationStudent.jButton1.requestFocusInWindow();
        }
        
        /**
         *  If the "Instructor" Version of the
         *  Account Creation Window is the GUI
         *  Class Which Spawned the Status Message
         *  GUI Window.
         */
        //if (formType == 0) {
            
        //}
        /**
         *  If the "Student" Version of the
         *  Account Creation Window is the GUI
         *  Class Which Spawned the Status Message
         *  GUI Window.
         */
        //else if (formType == 1) {
            
        //}
    }
    
    /**
     *  This Method is Used to Set the Display Text Message Font Size 
     *  Present Within the Current Instance of this GUI Window Form.
     *  
     *  @param value        The Integer Value Which Determines the Font
     *                      Size of the Display Message Value.
     */
    public void setStatusMessageFontSize(int value) {
        // Set the Status Message Font Size.
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, value));
    }
    
    /**
     *  This Method is Used to Set the Display Text Message Present
     *  Within the Current Instance of this GUI Window Form.
     * 
     *  @param value        The String Message Value that will be
     *                      Displayed on the Current Instance of the
     *                      Status Message Window Form.
     */
    public void setStatusMessageDisplayMessage(String value) {
        // Set the Status Message Value.
        jLabel6.setText(value);
    }
    
    /**
     *  This Method is Used to Set the Display Text Value of the "Instructor"
     *  Account Creation Error Message JLabel Located Under the "Confirm
     *  Password" Text Field.
     * 
     *  @param value        The Error / Status Message String
     *                      Value that will be Displayed Within
     *                      the Instructor Account Creation JLabel
     *                      Component.
     */
    public void setInstructorACStatusMessage(String value) {
        // Set the Display Text Message Value
        AccountCreationInstructor.jLabel2.setText(value);
    }
    
    /**
     *  This Method is Used to Set the Display Text Value of the "Student"
     *  Account Creation Error Message JLabel Located Under the "Confirm
     *  Password" Text Field.
     * 
     *  @param value        The Error / Status Message String
     *                      Value that will be Displayed Within
     *                      the Student Account Creation JLabel
     *                      Component.
     */
    public void setStudentACStatusMessage(String value) {
        // Set the Display Text Message Value
        AccountCreationStudent.jLabel2.setText(value);
    }
    
    /**
     *  This Method is Used to Show the Error / Status Message
     *  JLabel Located Within the Account Creation Instructor
     *  GUI Window Form.
     */
    public void showInstructorACStatusMessage() {
        // Show the Error / Status Message JLabel
        AccountCreationInstructor.jLabel2.setVisible(true);
    }
    
    /**
     *  This Method is Used to Show the Error / Status Message
     *  JLabel Located Within the Account Creation Student
     *  GUI Window Form.
     */
    public void showStudentACStatusMessage() {
        // Show the Error / Status Message JLabel
        AccountCreationStudent.jLabel2.setVisible(true);
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "First Name"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "First Name" String Value.
     */
    public void setInstructorACFirstNameFieldErrorAesthetics() {
        // Highlight "First Name" Field Background in Red.
        AccountCreationInstructor.jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        // Change "First Name" Field Font Color to Gray.
        AccountCreationInstructor.jTextField1.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "First Name"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "First Name" String Value.
     */
    public void setStudentACFirstNameFieldErrorAesthetics() {
        // Highlight "First Name" Field Background in Red.
        AccountCreationStudent.jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        // Change "First Name" Field Font Color to Gray.
        AccountCreationStudent.jTextField1.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Last Name"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Last Name" String Value.
     */
    public void setInstructorACLastNameFieldErrorAesthetics() {
        // Highlight "Last Name" Field Background in Red.
        AccountCreationInstructor.jTextField2.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Last Name" Field Font Color to Gray.
        AccountCreationInstructor.jTextField2.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Last Name"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Last Name" String Value.
     */
    public void setStudentACLastNameFieldErrorAesthetics() {
        // Highlight "Last Name" Field Background in Red.
        AccountCreationStudent.jTextField2.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Last Name" Field Font Color to Gray.
        AccountCreationStudent.jTextField2.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Email Address"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Email Address" String Value.
     */
    public void setInstructorACEmailAddressFieldErrorAesthetics() {
        // Highlight "Email Address" Field Background in Red.
        AccountCreationInstructor.jTextField3.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Email Address" Field Font Color to Gray.
        AccountCreationInstructor.jTextField3.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Email Address"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Email Address" String Value.
     */
    public void setStudentACEmailAddressFieldErrorAesthetics() {
        // Highlight "Email Address" Field Background in Red.
        AccountCreationStudent.jTextField3.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Email Address" Field Font Color to Gray.
        AccountCreationStudent.jTextField3.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Username"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Username" String Value.
     */
    public void setInstructorACUsernameFieldErrorAesthetics() {
        // Highlight "Username" Field Background in Red.
        AccountCreationInstructor.jTextField4.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Username" Field Font Color to Gray.
        AccountCreationInstructor.jTextField4.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "First Name"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Username" String Value.
     */
    public void setStudentACUsernameFieldErrorAesthetics() {
        // Highlight "Username" Field Background in Red.
        AccountCreationStudent.jTextField4.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Username" Field Font Color to Gray.
        AccountCreationStudent.jTextField4.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Confirm Username"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Confirm Username" String Value.
     */
    public void setInstructorACConfirmUsernameFieldErrorAesthetics() {
        // Highlight "Confirm Username" Field Background in Red.
        AccountCreationInstructor.jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Confirm Username" Field Font Color to Gray.
        AccountCreationInstructor.jTextField5.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Confirm Username"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Confirm Username" String Value.
     */
    public void setStudentACConfirmUsernameFieldErrorAesthetics() {
        // Highlight "Confirm Username" Field Background in Red.
        AccountCreationStudent.jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Confirm Username" Field Font Color to Gray.
        AccountCreationStudent.jTextField5.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Password"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Password" String Value.
     */
    public void setInstructorACPasswordFieldErrorAesthetics() {
        // Highlight "Password" Field Background in Red.
        AccountCreationInstructor.jPasswordField1.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Password" Field Font Color to Gray.
        AccountCreationInstructor.jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Password"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Password" String Value.
     */
    public void setStudentACPasswordFieldErrorAesthetics() {
        // Highlight "Password" Field Background in Red.
        AccountCreationStudent.jPasswordField1.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Password" Field Font Color to Gray.
        AccountCreationStudent.jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Instructor Account Creation "Confirm Password"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Confirm Password" String Value.
     */
    public void setInstructorACConfirmPasswordFieldErrorAesthetics() {
        // Highlight "Confirm Password" Field Background in Red.
        AccountCreationInstructor.jPasswordField2.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Confirm Password" Field Font Color to Gray.
        AccountCreationInstructor.jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Confirm Password"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Confirm Password" String Value.
     */
    public void setStudentACConfirmPasswordFieldErrorAesthetics() {
        // Highlight "Confirm Password" Field Background in Red.
        AccountCreationStudent.jPasswordField2.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Confirm Password" Field Font Color to Gray.
        AccountCreationStudent.jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Highlight the Student Account Creation "Student Identification Number"
     *  User Response Field. This Method is Invoked Whenever the User Input
     *  Causes an Error to Occur in the Account Creation Process which is Attributed to
     *  the Use of an Invalid or Non-Existing "Student Identification Number" String Value.
     */
    public void setStudentACStudentIdentificationNumberFieldErrorAesthetics() {
        // Highlight "Student Identification Number" Field Background in Red.
        AccountCreationStudent.jTextField6.setBackground(new java.awt.Color(255, 0, 0));
        // Change "Student Identification Number" Field Font Color to Gray.
        AccountCreationStudent.jTextField6.setForeground(new java.awt.Color(204, 204, 204));
    }
    
    /**
     *  This Method is Used to Set Which Icon will be Shown within the
     *  Current Instance of the Status Message Credentials Screen GUI Class.
     *  If the Error Type which Caused the Window Instance to be Spawned
     *  Deals with the User Failing to Input Information, then the JLabel
     *  Emblem will Show the Yellow Warning Message Icon. Otherwise, it
     *  will show the Red Warning Message Icon.
     * 
     *  @param value            The Integer Number Telling the Class Which
     *                          Warning Emblem Should Be Shown in the Status
     *                          Message Instance when it is Shown to the User.
     */
    public void setStatusMessageEmblem(int value) {
        /**
         * If the Integer Number is the Value of 0
         * then Display the Red Warning Message Emblem
         * Within the Form.
         */
        if (value == 0) {
            // Set the Display Emblem Icon.
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/warningemblemscaled.png"))); // NOI18N
        }
        /**
         * If the Integer Number is the Value of 1
         * then Display the Yellow Warning Message Emblem
         * Within the Form.
         */
        else if (value == 1) {
            // Set the Display Emblem Icon.
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/YMIcon75x75.png"))); // NOI18N
        }
        /**
         * If the Integer Number is any other Value,
         * then Display the Red Warning Message Emblem
         * Within the Form.
         */
        else {
            // Set the Display Emblem Icon.
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mothershipattendance/Image/warningemblemscaled.png"))); // NOI18N
        }
    }
    
    /**
     *  This Method is Used to Re-enable the User Response Components
     *  Present Within the Instructor Account Creation GUI Window Upon 
     *  Successful Task Completion.
     */
    public void enableCredentialsScreenComponents() {
        // Re-enable Instructor Account Creation GUI Window Components
        AccountCreationInstructor.setComponentEnablementStatus(true);
    }
    
    public void executeThreadTaskInstructor(int value) {
        
        /**
         *  Create String Object Which is Used to
         *  Hold the Custom Error Message Value Which
         *  Will be Displayed in the Account Creation
         *  Instructor Error Message JLabel.
         */
        String statusMessageValue = "";
        
        /**
         *  If the Account Creation Instructor GUI Form Has Determined that There
         *  are Multiple Fields Missing User Response Information Present, then
         *  Determine Which Fields are Missing the Information and Change their
         *  Aesthetic Properties. Additionally, Create a New Error Message
         *  String and Set the Custom Value as the Display Text Value of the
         *  Status Message JLabel in the Instructor Account Creation GUI Form.
         */
        if (value == 0) {
            
            // Retrieve the "Password" Value From the JPasswordField and Convert it to a String Object. 
            String passwordOne = new String(AccountCreationInstructor.jPasswordField1.getPassword());
            // Retrieve the "Confirm Password" Value From the JPasswordField and Convert it to a String Object. 
            String passwordTwo = new String(AccountCreationInstructor.jPasswordField2.getPassword());

            /**
             *  If the "First Name" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (AccountCreationInstructor.jTextField1.getText().equalsIgnoreCase("First Name")) {
                // Change Field Aesthetic Properties.
                setInstructorACFirstNameFieldErrorAesthetics();
            }
            /**
             *  If the "Last Name" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (AccountCreationInstructor.jTextField2.getText().equalsIgnoreCase("Last Name")) {
                // Change Field Aesthetic Properties.
                setInstructorACLastNameFieldErrorAesthetics();
            }
            /**
             *  If the "Email Address" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (AccountCreationInstructor.jTextField3.getText().equalsIgnoreCase("Email Address")) {
                // Change Field Aesthetic Properties.
                setInstructorACEmailAddressFieldErrorAesthetics();
            }
            /**
             *  If the "Username" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (AccountCreationInstructor.jTextField4.getText().equalsIgnoreCase("Username")) {
                // Change Field Aesthetic Properties.
                setInstructorACUsernameFieldErrorAesthetics();
            }
            /**
             *  If the "Confirm Username" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (AccountCreationInstructor.jTextField5.getText().equalsIgnoreCase("Confirm Username")) {
                // Change Field Aesthetic Properties.
                setInstructorACConfirmUsernameFieldErrorAesthetics();
            }
            /**
             *  If the "Password" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (passwordOne.equalsIgnoreCase("Password")) {
                // Change Field Aesthetic Properties.
                setInstructorACPasswordFieldErrorAesthetics();
            }
            /**
             *  If the "Confirm Password" User Response Field in the Instructor Account
             *  Creation GUI Form is Missing Information.
             */
            if (passwordTwo.equalsIgnoreCase("Confirm Password")) {
                // Change Field Aesthetic Properties.
                setInstructorACConfirmPasswordFieldErrorAesthetics();
            }
            
            // Set Status / Error Message Value.
            statusMessageValue = "Multiple Response Fields Contain Incorrect Information.";
        }
        else if (value == 1) {
            // Change Field Aesthetic Properties.
            setInstructorACFirstNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'First Name' Field.";
        }
        else if (value == 2) {
            // Change Field Aesthetic Properties.
            setInstructorACLastNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Last Name' Field.";
        }
        else if (value == 3) {
            // Change Field Aesthetic Properties.
            setInstructorACEmailAddressFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Email Address' Field.";
        }
        else if (value == 4) {
            // Change Field Aesthetic Properties.
            setInstructorACUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Username' Field.";
        }
        else if (value == 5) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Confirm Username' Field.";
        }
        else if (value == 6) {
            // Change Field Aesthetic Properties.
            setInstructorACPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Password' Field.";
        }
        else if (value == 7) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "Please Enter A Response For the 'Confirm Username' Field.";
        }
        else if (value == 8) {
            /**
             *  If the "First Name" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[0] == true || results[1] == true || results[2] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACFirstNameFieldErrorAesthetics();
            }
            /**
             *  If the "Last Name" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[3] == true || results[4] == true || results[5] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACLastNameFieldErrorAesthetics();
            }
            /**
             *  If the "Email Address" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[6] == true || results[7] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACEmailAddressFieldErrorAesthetics();
            }
            /**
             *  If the "Username" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[8] == true || results[9] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACUsernameFieldErrorAesthetics();
            }
            /**
             *  If the "Confirm Username" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[10] == true || results[11] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACConfirmUsernameFieldErrorAesthetics();
            }
            /**
             *  If the "Password" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[12] == true || results[13] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACPasswordFieldErrorAesthetics();
            }
            /**
             *  If the "Confirm Password" Field Contains Any Errors
             *  Highlight the Field as Containing an Error.
             */
            if (results[14] == true || results[15] == true) {
                // Change Field Aesthetic Properties.
                setInstructorACConfirmPasswordFieldErrorAesthetics();
            }
            
            // Set Status / Error Message Value.
            statusMessageValue = "Multiple Fields Contain Prohibited Characters or Whitespace.";
        }
        else if (value == 9) {
            // Change Field Aesthetic Properties.
            setInstructorACFirstNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'First Name' Field Response Contains Whitespace Characters.";
        }
        else if (value == 10) {
            // Change Field Aesthetic Properties.
            setInstructorACFirstNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'First Name' Field Contains Prohibited Numeric Characters.";
        }
        else if (value == 11) {
            // Change Field Aesthetic Properties.
            setInstructorACFirstNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'First Name' Field Contains Prohibited Special Characters.";
        }
        else if (value == 12) {
            // Change Field Aesthetic Properties.
            setInstructorACLastNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Last Name' Field Response Contains Whitespace Characters.";
        }
        else if (value == 13) {
            // Change Field Aesthetic Properties.
            setInstructorACLastNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Last Name' Field Contains Prohibited Numeric Characters.";
        }
        else if (value == 14) {
            // Change Field Aesthetic Properties.
            setInstructorACLastNameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Last Name' Field Contains Prohibited Special Characters.";
        }
        else if (value == 15) {
            // Change Field Aesthetic Properties.
            setInstructorACEmailAddressFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Email Address' Field Response Contains Whitespace Characters.";
        }
        else if (value == 16) {
            // Change Field Aesthetic Properties.
            setInstructorACEmailAddressFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Email Address' Field Contains Prohibited Special Characters.";
        }
        else if (value == 17) {
            // Change Field Aesthetic Properties.
            setInstructorACUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Username' Field Response Contains Whitespace Characters.";
        }
        else if (value == 18) {
            // Change Field Aesthetic Properties.
            setInstructorACUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Username' Field Contains Prohibited Special Characters.";
        }
        else if (value == 19) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Username' Field Response Contains Whitespace Characters.";
        }
        else if (value == 20) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Username' Field Contains Prohibited Special Characters.";
        }
        else if (value == 21) {
            // Change Field Aesthetic Properties.
            setInstructorACPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Password' Field Response Contains Whitespace Characters.";
        }
        else if (value == 22) {
            // Change Field Aesthetic Properties.
            setInstructorACPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Password' Field Contains Prohibited Special Characters.";
        }
        else if (value == 23) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Password' Field Response Contains Whitespace Characters.";
        }
        else if (value == 24) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Password' Field Contains Prohibited Special Characters.";
        }
        else if (value == 25) {
            // Change Field Aesthetic Properties.
            setInstructorACEmailAddressFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Email Address' Field Doesn't Meet the Ten Character Requirement.";
        }
        else if (value == 26) {
            // Change Field Aesthetic Properties.
            setInstructorACUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Username' Field Doesn't Meet the Seven Character Requirement.";
        }
        else if (value == 27) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmUsernameFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Username' Field Doesn't Meet the Seven Character Requirement.";
        }
        else if (value == 28) {
            // Change Field Aesthetic Properties.
            setInstructorACPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Password' Field Doesn't Meet the Eleven Character Requirement.";
        }
        else if (value == 29) {
            // Change Field Aesthetic Properties.
            setInstructorACConfirmPasswordFieldErrorAesthetics();
            // Set Status / Error Message Value.
            statusMessageValue = "The 'Confirm Password' Field Doesn't Meet the Seven Character Requirement.";
        }
        else if (value == 30) {
            
        }
        
        /**
        *  Set the Status Message Value as the Value Within
        *  the Error Message JLabel Present Within the Instructor 
        *  Account Creation GUI Form.
        */
        setInstructorACStatusMessage(statusMessageValue);

       /**
        *  Show the Instructor Account Creation GUI
        *  Windows Error Message JLabel Component.
        */
        showInstructorACStatusMessage();

       /**
        *  Enable the User Response Components Present
        *  Within the Account Creation Instructor GUI Form.
        */
        enableCredentialsScreenComponents();

       /**
        *  Request that the Main Event Queue Thread's Focus
        *  be Placed Upon the "Create Account" JButton within
        *  the Form. This is Done to Stop the Focus From
        *  Automatically being applied to the First User
        *  Response Field, which causes the Highlighted
        *  Field Aesthetics to Disappear.
        */
        requestFocusOnAccountCreationButtonComponent();
    }
    
    public void executeThreadTaskStudent(int value) {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusMessageAccountCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusMessageAccountCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusMessageAccountCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusMessageAccountCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusMessageAccountCreation(-1, -1, new boolean[1]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
    /**
    *  Create an Global Integer Variable Which is Responsible
    *  For Determining What Type of Error Has Occurred in the
    *  Account Creation Process. This Value will be Defined
    *  in as the Parameter Value that the GUI Class Instance is
    *  Instantiated With.
    */
    public int messageType;
    /**
     *  Create a Global Integer Variable Which is Responsible
     *  For Determining Which Account Creation GUI Window Form
     *  Has Invoked it. This Value will either be Defined as
     *  the Integer 0 or 1. The Definition of these Values is
     *  Provided Below:
     * 
     *  0   -   Instructor Account Creation Window
     * 
     *  1   -   Student Account Creation Window
     */
    public int formType;
    
    /**
     *  This Array Value is Used to Hold the Results of
     *  the Second Segment of the Validity Checking Process
     *  It will be Used should there be Multiple Response
     *  Fields that Contain Prohibited or Blank Characters.
     */
    public boolean[] results;
    
    /**
     *  This Class is an Implementation of the Java SwingWorker Interface,
     *  which is used to create Background Threads that can perform
     *  operations and make changes to the GUI Form. A Java Swing Program
     *  is run off a Special Kind of Thread Called an Event Queue Thread which
     *  is specifically made to Handle Events Such as ActionPerformed,
     *  MouseClicked, and FocusLost/FocusGained methods while being able
     *  to immediately return to its Original Task. This means that a regular
     *  Java Class or Java Thread, is unable to invoke Changes within a Java
     *  Swing Form without causing unprecedented, non-repeatable errors during
     *  Program Execution. Thus, to invoke Changes to the Swing Form without
     *  violating the Rules of the Main Event Queue Thread, we create an Instance
     *  of the Java SwingWorker Class. This SwingWorker Class is used to create
     *  a Second Background Event Queue Thread which is used to Free Up the
     *  Main Event Queue Thread of doing long taxing operations (So that it may
     *  focus on maintaining the Window Form's Overall Appearance [Look & Feel]),
     *  in addition to being able to invoke changes within the Swing Form without
     *  causing unprecedented unrepeatable errors.
     *  
     *  The TaskHandler Class is used to create and execute a Background Thread
     *  every time the User Clicks on one of the two JButton Components Located Within
     *  the form. Once these threads are executed, they will be used to either Retrieve
     *  and determine User Response Integrity before moving on to the Decryption Process
     *  or alter Component Information/Aesthetics.
     * 
     *  (Note: the doInBackground() method is the Equivalent of the run() method
     *  used when manipulating regular threads. This means that the doInBackground()
     *  method will immediately start once the Program invokes the execute() method
     *  on the new TaskHandler SwingWorker Class Instance. The done() method is invoked
     *  immediately after the doInBackground() method has finished its execution. Although
     *  there may be no Operations performed within the Method, it its required to have
     *  within every SwingWorker Interface.)
     */
    private class TaskHandler extends SwingWorker<Void,Void> {
        
        /**
        *  Create A Custom String Value Meant to Hold 
        *  the User Input Password Value
        */
        public String passwordValue = "";
        /**
        *  Create an Integer Variable Which is Responsible
        *  For Determining What Type of Task the Background
        *  Event Queue Thread will Execute.
        */
        public int task;
        
        /**
         *  This Constructor is Used to Create a New
         *  Instance of the Task Handler Thread and
         *  set the Error Type Integer Number Value
         *  which Determines what the Thread Does on
         *  Window Disposal.
         * 
         *  @param value        The Error / Status Message
         *                      Number that Tells the Background
         *                      SwingWorker Event Queue Thread
         *                      which Task to Execute.
         */
        public TaskHandler(int value) {
            // Set the Task Type.
            task = value;
        }
        
        /**
         * Method for Separate EventQueue Thread
         * to Execute.
         **/
        @Override
        protected Void doInBackground() throws Exception {
            
            /**
             *  Create Custom String Variable to Hold the
             *  Newly Generated Custom Message Which will be
             *  Displayed Under the Password Field in Either
             *  the Instructor or Student Account Creation
             *  GUI Window Form.
             */
            String displayMessage = "";
            
            if (formType == 0) {
                executeThreadTaskInstructor(task);
            }
            else if (formType == 1) {
                executeThreadTaskStudent(task);
            }
            
            /**
             * We will always Return a Null
             * Value for any SwingWorker Thread.
             */
            return null;
        }
    }
}
